### ISSUE TITLE
RuntimeError: destination port 0 out of range for Power(4) in gnuradio

### ISSUE THREAD

**Issue by oislos** [sq5bpf/telive#29]
I tried to run a flow graph, but the plot does not come out and error is occurred as:

Generating: '/Users/pc/Documents/Gnuradio/ECE 440/Lab 1/top_block.py'

Executing: /opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -u /Users/pc/Documents/Gnuradio/ECE 440/Lab 1/top_block.py

Traceback (most recent call last):
  File "/Users/pc/Documents/Gnuradio/ECE 440/Lab 1/top_block.py", line 269, in <module>
    main()
  File "/Users/pc/Documents/Gnuradio/ECE 440/Lab 1/top_block.py", line 245, in main
    tb = top_block_cls()
  File "/Users/pc/Documents/Gnuradio/ECE 440/Lab 1/top_block.py", line 203, in __init__
    self.power_0 = power()
  File "/Users/pc/Documents/Gnuradio/ECE 440/Lab 1/power.py", line 85, in __init__
    self.connect((self.blocks_rms_xx_0, 0), (self, 0))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gnuradio/gr/hier_block2.py", line 48, in wrapped
    func(self, src, src_port, dst, dst_port)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gnuradio/gr/hier_block2.py", line 111, in connect
    self.primitive_connect(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/gnuradio/gr/runtime_swig.py", line 4531, in primitive_connect
    return _runtime_swig.top_block_sptr_primitive_connect(self, *args)
RuntimeError: destination port 0 out of range for Power(4)

I don't know what the problem is.

**Comment by sq5bpf** [comment]
judging from the paths in your message you're using some non-standard setup, so you're on your own.

also you're using python3, and this currently works with python 2.7 only
